### index
GET /api/items HTTP/1.1
Host: localhost
Accept: application/json

### show
GET /api/items/1 HTTP/1.1
Host: localhost
Accept: application/json

### register
POST /api/register
Host: localhost
Accept: application/json
content-type: application/json

{
    "name": "bbb",
    "email": "taro@example.com",
    "password": "password",
    "tel": "0000000",
    "address": "千葉"
}

### login
POST /api/login
Host: localhost
Accept: application/json
content-type: application/json

{
    "name": "bbb",
    "email": "taro@example.com",
    "password": "password",
    "tel": "0000000",
    "address": "千葉"
}

### store
POST /api/items
Host: localhost
Authorization: Bearer 5|oUWtMHTDhANkYpt1aVZWbwsEbR53axRAYj0zrXwg
Accept: application/json
Content-Type: multipart/form-data; boundary=storeform


--storeform
Content-Disposition: form-data; name="category_id";
Content-Type: TEXT

3

--storeform
Content-Disposition: form-data; name="lost_desc";
Content-Type: TEXT

バスの中

--storeform
Content-Disposition: form-data; name="feature";
Content-Type: TEXT

灰色

--storeform
Content-Disposition: form-data; name="file"; filename="/Users/alisa/egg01.jpeg";
Content-Type: image/jpeg

< /Users/alisa/egg01.jpeg
--storeform

### update
POST /api/items/1
Host: localhost
Authorization: Bearer 5|oUWtMHTDhANkYpt1aVZWbwsEbR53axRAYj0zrXwg
Accept: application/json
Content-Type: multipart/form-data; boundary=updateform

--updateform
Content-Disposition: form-data; name="_method";
Content-Type: TEXT

PUT

--updateform
Content-Disposition: form-data; name="category_id";
Content-Type: TEXT

3

--updateform
Content-Disposition: form-data; name="lost_desc";
Content-Type: TEXT

"バスの中"

--updateform
Content-Disposition: form-data; name="feature";
Content-Type: TEXT

"灰色"

--updateform
Content-Disposition: form-data; name="file"; filename="/Users/alisa/egg02.jpeg";
Content-Type: image/jpeg

< /Users/alisa/egg02.jpeg
--updateform

### update
PUT /api/items/1
Host: localhost
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|oUWtMHTDhANkYpt1aVZWbwsEbR53axRAYj0zrXwg

{
    "category_id": 3,
    "lost_desc": "バスの中",
    "feature": "灰色"
}

### destroy
DELETE /api/items/5 HTTP/1.1
Host: localhost
Accept: application/json


### index
GET /api/categories HTTP/1.1
Host: localhost
Accept: application/json