### index
GET /api/items HTTP/1.1
Host: localhost
Accept: application/json

### show
GET /api/items/1 HTTP/1.1
Host: localhost
Accept: application/json

### store
POST /api/items
Host: localhost
Accept: application/json
content-type: application/json

{
    "lost_desc": "八丁堀",
    "category_id": 1,
    "feature" : "赤い",
    "file": "https://storage.googleapis.com/atta2-app.appspot.com/items/BRUwqIbsEwfM3tTjzYQWtgUwRxVXtbnI5J1CYw3A.png?GoogleAccessId=firebase-adminsdk-vfjcd%40atta2-app.iam.gserviceaccount.com&Expires=1637805013&Signature=IQ%2FkqGRuZRgeDSS%2FWPiVlpNcwFxxGGMNr1TvzUoAQREkVU%2BmokhnaJsoyuWAVx2yZ862ujPmQ%2BQyOFrxjnRt4FgV1ffUkdmH4wxaGQjrMFoO3pUcyJZfg75TlPBQXadkurmkBW2O5fYAjl2NW44eRP9bbWgo6OvkrgfE%2B3agErgq65aUA3kiSvVFi9UibKq0RjyuKGs3vFmHpFAIsa6LAPy1WvtPJixNF5sUetg1jFGQN9HiGeIgrqES8qdETOgtGmGUrr4YWTcFmdd571XDRDssG6Mnhy%2BaWCWdZDgr1yYSucTdUycEV1yFYwDFWB2jO0Ng%2BOblcuvE46IYQRKbUA%3D%3D",
}

### destroy
DELETE /api/items/2 HTTP/1.1
Host: localhost
Accept: application/json

### register
POST /api/register
Host: localhost
Accept: application/json
content-type: application/json

{
    "name": "bbb",
    "email": "taro@example.com",
    "password": "password",
    "tel": "0000000",
    "address": "千葉"
}

### login
POST /api/login
Host: localhost
Accept: application/json
content-type: application/json

{
    "name": "bbb",
    "email": "taro@example.com",
    "password": "password",
    "tel": "0000000",
    "address": "千葉"
}